/**
 * Holds all texts used by application
 */
const Texts = Object.freeze({
    //error messages
    PIPEWAY_DATA_NOT_FOUND: "Dados de dimensionamento não encontrados!",
    PIPE_SEGMENT_NOT_FOUND: "Trecho de tubulação não encontrada!",
    NULL_FILE_HANDLE: "Manipulador de arquivos nulo",
    INVALID_FILE_DATA_STRUCTURE: "Estrutura de dados do arquivo é inválida!",
    PIPESEGMENT_DATA_NOT_FOUND: "Dados de Trecho de tubulação não encontrados!",
    NAME_ALREADY_USED: "Nome já utilizado, escolha outro!",
    PIPESEGMENT_IS_A_PREDECESSOR_SEGMENT: "O Trecho de tubulação antece outro trecho e não pode ser deletado!",
    INVALID_PREDECESSOR_PIPESEGMENT_ID: "Id de trecho antecessor invalido!",
    EMPTY_FORM_FIELD_ERROR: "Não é permito campos vazios no formulário!",
    PIPESEGMENT_ID_EQUAL_TO_PREDECESSOR_PIPESEGMENT_ID: "O trecho atual não pode anteceder ele mesmo!",
    PUMPING_SEGMENT_NOT_FOUND: "Trecho de tubulação de recalque não encontrado!",
    NOT_ALLOWED_SAVE: "Não é possível salvar!",

    //warnings
    VELOCITY_LIMIT_WARNING: "Velocidade no trecho maior que 3,0 m/s!",
    PRESSURE_MIN_LIMIT_WATNING: "Pressão no final do trecho inferior a 10kPa ou 1 mca!",
    PRESSURE_MAX_LIMIT_WATNING: "Pressão no final do trecho superior a 400kPa ou 40 mca!",
    INADEQUATE_DIAMETERS_WARNING: "Diametro da sucção e recalque inadequados!",
    FLOW_RATE_WARNING: "Vazão escolhida é inferior a 15% do consumo diário!",

    //html texts
    APP_NOT_WORK_IN_THIS_BROWSER: "A aplicação necessita do browser Google Chrome para funcionar!",
    TITLE: "H-calc",
    SUBTITLE: "Dimensionamento de instalações hidráulicas",
    FOOTER: "H-calc",
    NEW: "Novo",
    SAVE: "Salvar",
    OPEN: "Abrir",
    TOOLS: "Ferramentas",
    CANCEL: "Cancelar",
    DELETE: "Deletar",
    EDIT: "Editar",
    REPORT: "Relatório",
    ADD_PIPE_SEGMENT: "Adicionar trecho",
    NAME: "Nome",
    PIPEWAY: "Projeto",
    SEGMENT: "Trecho",
    SEGMENTS: "Trechos",
    UNIT: "Unidade",
    MATERIAL: "Material",
    SMOOTH: "PVC / Cobre",
    ROUGH: "Aço Carbono / Ferro Fundido",
    NOMINAL_DIAMETERS: "Diâmetros nominais",
    NOMINAL_DIAMETER: "Diâmetro nominal",
    FLOW_RATE_CALCULATOR: "Calcularora de vazão",
    PUMPING_CALCULATOR: "Calculadora de bomba",
    HYDROMETER: "hidrômetro",
    SANITARY_EQUIPMENTS: "Equipamentos sanitários",
    PIPE_CONNECTIONS: "Conexões",
    LENGTH: "Comprimento",
    HEIGHT_VARIATION: "Variação de nível",
    LEGEND_FOR_VARIABLE: "Legenda",
    INITIAL_PRESSURE: "Pressão inicial",
    PREDECESSOR_PIPESEGMENT: "Trecho anterior",
    PREDECESSOR_PIPESEGMENT_ID: "ID do trecho anterior",
    REGISTERS: "Registros",
    FLOW_RATE: "Vazão",
    FLOW_RATE_WEIGHTS: "Pesos para cálculo de vazão",
    VELOCITY: "Velocidade",
    PRESSURE_LOSS: "Perda de carga",
    UNITARY_PRESSURE_LOSS: "Perda de carga unitaria",
    PRESSURE: "Pressão",
    OK: "OK",
    NONE: "-",
    PARAMETERS: "Parâmetros",
    PIPESEGMENT_INFO: "informações do trecho",
    DO_YOU_HAVE_TO_DELETE_THE_PIPE_SEGMNET: "Tem certeza que quer deletar o trecho",
    DO_YOU_HAVE_TO_DELETE_THE_PUMPING_SEGMNET: "Tem certeza que quer deletar o dimensionamento de recalque",
    CONFIGURATIONS: "Configurações",
    DECIMAL_PLACES: "Casas decimais",
    DECIMAL_SEPARATOR: "Separador decimal",
    EQUIVALENT_LENGTH: "Comprimento equivalente",
    REAL_LENGTH: "Comprimento real",
    SUM_OF_WEIGHTS: "Somatória de pesos",
    PUMPING_POWER_CALCULATED: "Potência calculada",
    PUMPING_POWER_INDICATED: "Potencia recomendada",
    DIMENSIONING_PUMPING: "Dimensionar recalque",
    THERE_ARE_NOT_SEGMENTS: "Não há trechos de tubulação dimensionados!",
    THERE_ARE_NOT_PUMPING_SEGMENT: "Não há tubulação de recalque dimensionada!",
    MANOMETRIC_HEIGHT: "Altura manométrica",
    PUMP_POWER: "Potencia da bomba",
    PUMPING_SEGMENT: "recalque",
    SUCTION_SEGMENT: "sucção",
    PUMPING_INFO: "Informações do dimensionamento do recalque",
    DIMENSIONATING_INFO: "Informações do dimensionamento da rede água fria",
    DAILY_CONSUMPTION: "Consumo diario",
    PUMP_YIELD: "Rendimento da bomba",
    SELECTED: "Selecionada",
    CALCULATED: "Calculada",
    PUMPING_TIME: "Tempo de bombeamento",
    REPORT_TITLE: "Relatório de Cálculo",
    DIAMETER: "Diametro",
    PIPE_QUANTITATIVE: "Quantitativo de tubulação e conexões",

    //Variables
    VAR_PRESSURE: "p",
    VAR_INITIAL_PRESSURE: "p0",
    VAR_FLOW_RATE: "Q",
    VAR_VELOCITY: "v",
    VAR_NOMINAL_DIAMETER: "DN",
    VAR_UNITARY_PRESSURE_LOSS: "J",
    VAR_PRESSURE_LOSS: "λ",
    VAR_EQUIVALENT_LENGTH: "Le",
    VAR_REAL_LENGTH: "Lr",
    VAR_HEIGHT_VARIATION: "Δh",
    VAR_SUM_OF_WEIGHTS: "ΣP",
    VAR_MAX_FLOW_RATE: "Qmax",
    VAR_MANOMETRIC_HEIGHT: "H",
    VAR_PUMP_POWER: "PB",
    VAR_PUMPING_TIME: "t",
    VAR_DAILY_CONSUMPTION: "Cd",
    VAR_PUMP_YIELD: "RB",
    

    //Pipe connections
    J90: "Joelho 90⁰",
    J45: "Joelho 45⁰",
    C90: "Curva 90⁰",
    C45: "Curva 45⁰",
    TPD: "Tê passagem direta",
    TPL: "Tê passagem lateral",
    TPBL: "Tê de passagem bilateral",
    SC: "Saída de canalização",
    EN: "Entrada normal",
    EB: "Entrada de borda",
    RGA: "Registro de gaveta",
    RGL: "Registro de globo",
    RAN: "Registro de ângulo",
    VPC: "Válvula de pé e crivo",
    VRL: "Válvula de retenção leve",
    VRP: "Válvula de retenção pesada",

    //Sanitary Equipments
    BSC: "Bacia sanitária com caixa acoplada",
    BSV: "Bacia sanitária com valvula de descarga",
    BH: "Banheira",
    BE: "Bebedouro",
    BI: "Bidê",
    CHD: "Chuveiro tipo ducha",
    CH: "Chuveiro elétrico",
    LVRP: "Máquina de lavar roupas/pratos",
    LV: "Lavatório",
    MCC: "Mictório com caixa acoplada",
    MCV: "Mictório com válvula de descarga",
    PI: "Pia",
    PITE: "Pia - torneira elétrica",
    TQ: "Tanque",
    TJL: "Torneira de jardim/lavagem geral",

})